# Generated by Django 5.1.5 on 2025-02-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhoodgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MarketplaceItem',
        ),
        migrations.DeleteModel(
            name='NeighborhoodGroup',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
