# Generated by Django 5.1.5 on 2025-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('GJ', 'Gujarat')], default='KL', max_length=2),
        ),
    ]
